# Generated by Django 4.0.3 on 2022-03-07 11:37

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('date', models.DateField(verbose_name='fecha')),
                ('name', models.CharField(max_length=250, verbose_name='nombre')),
                ('desc', wagtail.core.fields.RichTextField(blank=True)),
                ('doc', models.URLField()),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
            },
        ),
    ]
