# Generated by Django 4.0.3 on 2022-03-13 19:26

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_contactpage_from_address_contactpage_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Introducción'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto de confirmación'),
        ),
    ]
